DATA_FOLDER : /u01/Intern/chinhdv/DATA/thangmay/data

train_csv : [
    /u01/Intern/chinhdv/DATA/thangmay/data/data_elevator.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
]
val_csv : [
    /u01/Intern/chinhdv/DATA/thangmay/data/data_elevator.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    /u01/Intern/chinhdv/DATA/thangmay/data/bending_down.csv,
    ]

classes:
  label: [bending-down, human, object, bike]

format_index: True

task_weights : [1]
class_weights:
  label: [2,1,1,1]

