# DATA_FOLDER : /u01/Intern/chinhdv/DATA/milk/all_crop_data_origin
# train_csv : /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_train_1103.csv
# val_csv: /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_val_1103.csv
DATA_FOLDER : /u01/DATA/HUMAN_ATTRIBUTE/PA_100K/data

train_csv : [
    /u01/Intern/chinhdv/code/multi-task-classification/trainPA100K.csv
]
val_csv : [
    /u01/Intern/chinhdv/code/multi-task-classification/valPA100K.csv
    ]

classes:
  age         : [0-18, 18-55, 55+] 
  gender      : [female, male]
#   shape       : [thin,fat,kid]
#   hair        : [long_hair, short_hair, bald, none]
  hat         : ["no", "yes"]
  glasses     : ["no", "yes"]
#   face_mask   : ["yes", "no"]
  body_pose   : [front_pose, side_pose, turn_back_pose]
#   visible     : [upperbody, fullbody, none]
  backpack    : ["no", "yes"]
  handbag     : ["no", "yes"]
  ub_length   : [short, long]
  lb_length   : [short, long]
#   action      : [standing, sitting, bending-down, other]
  holding_object: ["no", "yes"]
#   crowd       : ["yes","no"]


# age, gender, shape, hair, hat, glasse


format_index: True

task_weights : [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]
class_weights:
    age: [3,1,3]
    gender: [1,1]
    hat         : [1, 1]
    glasses     : [1, 1]
    body_pose   : [1, 1, 1]
    backpack    : [2, 1]
    handbag     : [1, 5]
    ub_length   : [1, 1]
    lb_length   : [1, 1]
    holding_object: [1, 10]
