img_size : 224
padding : True
epoch: 500
save_best: True
device : cuda:0
#augment params

hsv : {
  hgain : 0.5,
  sgain : 0.5,
  vgain : 0.5
} 

# geometric augmentation

fliplr: 0.5
rotate: {
  angle : 45, #(degree)
  mode : reflect, # or constant
  border_constant: [255,255,255]
}
ShearX : 3 
ShearY : 4
TranslateX : 2
TranslateY : 2
Sharpness : 

# photometric augmentation

hist_equalize : True
invert : False                # return 255 - image
mix_up_gray_scale : True      # convert img to grayscale and mixup with original image.
adjust_brightness : 0.5,1.5   # mixup with white img
solarize : {                  # For each pixel in the image, select the pixel
  Threshold : 255              # if the value is less than the threshold.
                              # Otherwise, subtract 255 from the pixel.
} 
posterize: {                  # shift right bit values and left shift ( equivalent clip value ) it so strong augment
  bits : 4                    #in range(0,8) , 4 is no-augment
}
contrast : True               # mixup original image with a mean pixel-value image.     

