# DATA_FOLDER : /u01/Intern/chinhdv/DATA/milk/all_crop_data_origin
# train_csv : /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_train_1103.csv
# val_csv: /u01/Intern/chinhdv/code/M_classification_torch/config/a/76classes_val_1103.csv
DATA_FOLDER : /u01/Intern/chinhdv/github/auto_upload_cvat/hmat

train_csv : [
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0000.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0001.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0002.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0003.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0004.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0005.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0006.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0007.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0008.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0009.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0010.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0011.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0012.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0013.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0014.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0015.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0016.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0017.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0018.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0019.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0020.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0021.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0022.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0023.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0024.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0025.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0026.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0027.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0028.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0029.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0030.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0031.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0032.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0033.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0034.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0035.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0036.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0037.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0038.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0039.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0040.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0041.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0042.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0043.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0044.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0045.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0046.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0047.csv,
    # /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0048.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0049.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0050.csv
]
val_csv : [
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0001.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0005.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0009.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0014.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0020.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0027.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0031.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0038.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0044.csv,
    /u01/Intern/chinhdv/github/auto_upload_cvat/csv_hmat/New_Human_Attributes_task_0048.csv,
    ]

classes:
    age: [children, middle, old] 
    gender: [female, male]

format_index: False

task_weights : [3, 1]
class_weights:
    age: [5,1,5]
    gender: [1,1]
